trigger: 
- main

pool:
  name: agents-ka-jhund


stages:
##init plan validate stages:
- stage: Plan
  displayName: Terraformplanstage
  jobs:
  - job : terraforminit
    displayName: Terraformjob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Parent Module'
        backendServiceArm: 'My_connection'
        backendAzureRmStorageAccountName: 'storageassig1912'
        backendAzureRmContainerName: 'blobcon'
        backendAzureRmKey: 'terraform.tfstate'

    # - task: TerraformTask@5
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'init'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/Parent-Module'


    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Parent Module'
        environmentServiceNameAzureRM: 'My_connection'


## security scanning stages:
- stage: securityscanning
  displayName: scanningvalastage
  jobs:
  - job : tfseec
    displayName: tfsec
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: '(System.DefaultWorkingDirectory)'

    













## manual validation stages:


## apply stages:






